name: Deploy
on:
  push: 
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run generate
      - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                branch: gh-pages # The branch the action should deploy to.
                folder: dist # The folder the action should deploy.